version: '3.3'

services: 
    nginx:latest:

        image: httpd  
        ports: 
            
            - 8080:80
        volumes: 
            - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf

            - ./my-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

            - ./maps:/usr/local/apache2/htdocs/maps